print("")
print(" INÍCIO DO PROGRAMA ")
print()
print("Para realizar opeções matemáticas em pitos basta informar a operação com os números e os símbolos.")
print()
print("----------------------------------------------------------")
print("| Operação de soma                      |  2 + 2  = ", 2 + 2, "  |")
print("| Operação de subtração                 |  2 - 2  = ", 2 - 2, "  |")
print("| Operação de multiplicação             |  2 * 2  = ", 2 * 2, "  |")
print("| Operação de disisão                   |  2 / 2  = ", 2 / 2, "|")
print("| Operação de exponenciação             |  2 ** 3 = ", 2 **3, "  |")
print("| Operação de módulo (resto da divisão) |  10 % 3 = ", 10 % 3, "  |")
print("----------------------------------------------------------")
print()
print(" FIM DO PROGRAMA ")
