print()
print("### INÍCIO DO PROGRAMA")
print()

print("Para a manipulação de arquivos nós devemos utilizar: ")
print('Função open')
print('Variável = open(nome, modo)')
print('O nome é o caminho completo do arquivo')
print('O modo é uma sigla de como o arquivo será aberto')
print()
print('MODO {:^6} FUNÇÃO {:^20}')
print('{:=^14} {: ^4} {:=^90}' .format(' MODO ', '||', ' FUNÇÃO '))
print('{:^14} {: ^4} {:<60}' .format('r', '||', 'Somente leitura'))
print('{:^14} {: ^4} {:<60}' .format('w', '||', 'Escrita (caso o arquivo já exista, ele será apagado e um novo arquivo vazio será criado)'))
print('{:^14} {: ^4} {:<60}' .format('a', '||', 'Leitura e Escrita (adiciona o novo conteúdo ao fin do arquivo)'))
print('{:^14} {: ^4} {:<60}' .format('r+', '||', 'Leitura e Escrita'))
print('{:^14} {: ^4} {:<60}' .format('w+', '||', 'Escrita (o modo w+, assim como o w, também apaga o conteúdo anterior do arquvio)'))
print('{:^14} {: ^4} {:<60}' .format('a+', '||', 'Leitura e Escrita (abre o arquivo para atualização)'))
print()

print()
print("### FIM DO PROGRAMA")